#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

#==================================================================================================
name: cine-room
#==================================================================================================

settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  bundleIdPrefix: br.com.tonon
  deploymentTarget:
    iOS: "14.0"

#==================================================================================================
targets:
#==================================================================================================

  cine-room:

    platform: iOS
    type: application
    
    sources:
      - path: cine-room

    info:
      path: cine-room/Resources/Info.plist
      properties:
        UISupportedInterfaceOrientations: []
        NSAppTransportSecurity: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
      
    postCompileScripts:
      - script: |
                export PATH="$PATH:/opt/homebrew/bin"
                if which swiftlint > /dev/null; then
                  swiftlint
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        name: Run SwiftLint
